### ISSUE TITLE
Multiline comments

### ISSUE THREAD

**Issue by jluttrell** [tylermurry/ado-pr-auto-comment#1]
Hi! First off thanks for creating this task. I just started to use it and it works great.

One thing though is I have a use case for a *single* multi-line comment, however adding new lines in `comments` input creates a comment per line (which I see you [split on "\n" here](https://github.com/tylermurry/ado-pr-auto-comment/blob/main/task/src/task.ts#L20)).

Is there a workaround or perhaps implement a flag that we can set to indicate whether to treat newlines as a new comment or have everything as a single comment? Or may be easiest to just make `comments` an array. 

i.e. 

```yml
comments:
  - This is
    my multi line
    comment
  - Second comment
  - ...
```

I'm happy to open a PR. Thanks!

**Comment by tylermurry** [comment]
Thanks for the issue, @jluttrell!

Originally, I wanted to do exactly what you described with the array. However, the pipeline syntax limits you to what you can do in the UI which does not have the concept of an "array" or "multi-select".

Open to ideas, but I think the most straight-forward way to achieve this is to introduce a (customizable) newline separator. For example:

```yml
- task: pr-auto-comment@1
  inputs:
    accessToken: '$(System.AccessToken)'
    newlineSeparator: "||"
    comments: |
      some||multi-line||comment
      another comment
```

The benefits to me are that it's easy to implement, visually clear and doesn't try to bend yaml backwards. Thoughts? 

I'm also very open to you submitting a PR for this issue!
